reminderapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "reminderapp"
urlpatterns = [
    # ex: /reminder/
    path("", views.indexView.as_view(), name = "index"),
    # ex: /reminder/5/
    # path("<int:question_id>/", views.detail, name = "detail"),
    path("<int:pk>/", views.DetailView.as_view(), name='detail'),
    # ex: /reminder/5/results/
    # path("<int:question_id>/results/", views.results, name = "results"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name='results'),
    # ex: /reminder/5/vote/
    path("<int:question_id>/vote/", views.vote, name = "vote"),

]

reminderproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    # Reminder project urls
    # path("admin/", admin.site.urls),
    path("admin/", admin.site.urls),


    # Reminder app urls
    path("", include("reminderapp.urls")),
]

reminderapp/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now()-datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

reminderapp/views.py
from django.db.models import F
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.urls import reverse
from django.views import generic 

from .models import Question, Choice


# Create your views here.

class indexView(generic.ListView):
    template_name = "reminderapp/index.html"
    context_object_name = "latest_question_list"
    
    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]
    
class DetailView(generic.DetailView):
    model = Question
    template_name = "reminderapp/detail.html"
    
class ResultsView(generic.DetailView):
    model = Question
    template_name = "reminderapp/results.html"
    

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        #Redisplay the question voting form
        return render(
            request,
            "reminderapp/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Allways return an HttpResponseRedirect after succesfully dealing 
        # with POST data. This prevents data from being posted twice if a user hits the 
        # Back button.
        return HttpResponseRedirect(reverse("reminderapp:results", args=(question_id,)))




# def index(request):
#     # latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     # template = loader.get_template("reminderapp/index.html")
#     # context = {
#     #     "latest_question_list":  latest_question_list,
#     # }
#     # return HttpResponse(template.render(context, request))
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     print(latest_question_list)
#     context = {"latest_question_list": latest_question_list }
#     return render(request, "reminderapp/index.html", context)

# def detail(request, question_id):
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404("Question does not exist / Spørsmålet eksisterer ikke.")
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "reminderapp/detail.html", {"question": question})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "reminderapp/results.html", {"question": question})

reminderapp/templates/reminderapp/detail.html
{% comment %} from view.py: question {% endcomment %}


<h1>Question:<br> {{ question.question_text }}</h1><br>
<form action="{% url 'reminderapp:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

reminderapp/templates/reminderapp/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        {% comment %} <li><a href="/reminder/{{ question.id }}/">{{ question.question_text }} {{question.id }}</a></li> {% endcomment %}
        {% comment %} <li><a href="{% url 'reminderapp:detail' question.id %}"> {{ question.question_text }} </a></li> {% endcomment %}
        <li><a href="{% url 'reminderapp:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

reminderapp/templates/reminderapp/results.html
{% comment %} from results.vies: question {% endcomment %}

<h1 {{ question.question_text }}> </h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li> {{ choice.choice_text}} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}
    </li>
    {% endfor %}
</ul>

<a href="{% url 'reminderapp:detail' question.id %}"> Vote again? </a>

reminderapp/templates/reminderapp/vote.html
Under construction !